// <auto-generated />
using System;
using HospitalSystemTeamTask;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalSystemTeamTask.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250210114102_inisialcreate")]
    partial class inisialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HospitalSystemTeamTask.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookingID"));

                    b.Property<DateTime?>("BookingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<int?>("PID")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<bool>("Staus")
                        .HasColumnType("boolean");

                    b.HasKey("BookingID");

                    b.HasIndex("CID");

                    b.HasIndex("PID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.Branch", b =>
                {
                    b.Property<int>("BID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BID"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BID");

                    b.HasIndex("BranchName")
                        .IsUnique();

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.BranchDepartment", b =>
                {
                    b.Property<int>("BID")
                        .HasColumnType("integer");

                    b.Property<int>("DepID")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentCapacity")
                        .HasColumnType("integer");

                    b.HasKey("BID", "DepID");

                    b.HasIndex("DepID");

                    b.ToTable("branchDepartments");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.Clinic", b =>
                {
                    b.Property<int>("CID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CID"));

                    b.Property<int?>("AssignDoctor")
                        .HasColumnType("integer");

                    b.Property<int>("BID")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("ClincName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<int>("DepID")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SlotDuration")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("CID");

                    b.HasIndex("AssignDoctor");

                    b.HasIndex("BID");

                    b.HasIndex("ClincName")
                        .IsUnique();

                    b.HasIndex("DepID");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.Department", b =>
                {
                    b.Property<int>("DepID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("DepID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.Doctor", b =>
                {
                    b.Property<int>("DID")
                        .HasColumnType("integer");

                    b.Property<int?>("CID")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentBrunch")
                        .HasColumnType("integer");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DepId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("JoiningDate")
                        .HasColumnType("date");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkingYear")
                        .HasColumnType("integer");

                    b.HasKey("DID");

                    b.HasIndex("CID");

                    b.HasIndex("CurrentBrunch");

                    b.HasIndex("DepId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.Patient", b =>
                {
                    b.Property<int>("PID")
                        .HasColumnType("integer");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.PatientRecord", b =>
                {
                    b.Property<int>("RID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RID"));

                    b.Property<int>("BID")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<int>("DID")
                        .HasColumnType("integer");

                    b.Property<string>("Inspection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PID")
                        .HasColumnType("integer");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("VisitTime")
                        .HasColumnType("interval");

                    b.HasKey("RID");

                    b.HasIndex("BID");

                    b.HasIndex("DID");

                    b.HasIndex("PID");

                    b.ToTable("PatientRecords");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.User", b =>
                {
                    b.Property<int>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("image")
                        .HasColumnType("text");

                    b.HasKey("UID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.Booking", b =>
                {
                    b.HasOne("HospitalSystemTeamTask.Models.Clinic", "Clinic")
                        .WithMany("Bookings")
                        .HasForeignKey("CID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSystemTeamTask.Models.Patient", "Patient")
                        .WithMany("Bookings")
                        .HasForeignKey("PID");

                    b.Navigation("Clinic");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.BranchDepartment", b =>
                {
                    b.HasOne("HospitalSystemTeamTask.Models.Branch", "Branch")
                        .WithMany("BranchDepartments")
                        .HasForeignKey("BID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSystemTeamTask.Models.Department", "Department")
                        .WithMany("BranchDepartments")
                        .HasForeignKey("DepID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.Clinic", b =>
                {
                    b.HasOne("HospitalSystemTeamTask.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("AssignDoctor");

                    b.HasOne("HospitalSystemTeamTask.Models.Branch", "Branch")
                        .WithMany("Clinics")
                        .HasForeignKey("BID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSystemTeamTask.Models.Department", "Department")
                        .WithMany("Clinics")
                        .HasForeignKey("DepID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Department");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.Doctor", b =>
                {
                    b.HasOne("HospitalSystemTeamTask.Models.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("CID");

                    b.HasOne("HospitalSystemTeamTask.Models.Branch", "Branch")
                        .WithMany("Doctors")
                        .HasForeignKey("CurrentBrunch")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSystemTeamTask.Models.User", "User")
                        .WithMany("Doctors")
                        .HasForeignKey("DID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSystemTeamTask.Models.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Clinic");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.Patient", b =>
                {
                    b.HasOne("HospitalSystemTeamTask.Models.User", "User")
                        .WithMany("Patients")
                        .HasForeignKey("PID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.PatientRecord", b =>
                {
                    b.HasOne("HospitalSystemTeamTask.Models.Branch", "Branch")
                        .WithMany("PatientRecords")
                        .HasForeignKey("BID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSystemTeamTask.Models.Doctor", "Doctor")
                        .WithMany("PatientRecords")
                        .HasForeignKey("DID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSystemTeamTask.Models.Patient", "Patient")
                        .WithMany("PatientRecords")
                        .HasForeignKey("PID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.Branch", b =>
                {
                    b.Navigation("BranchDepartments");

                    b.Navigation("Clinics");

                    b.Navigation("Doctors");

                    b.Navigation("PatientRecords");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.Clinic", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.Department", b =>
                {
                    b.Navigation("BranchDepartments");

                    b.Navigation("Clinics");

                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.Doctor", b =>
                {
                    b.Navigation("PatientRecords");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.Patient", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("PatientRecords");
                });

            modelBuilder.Entity("HospitalSystemTeamTask.Models.User", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
